version: "2"

volumes:
  gems:
    driver: local
services:
  whally:
    image: ruby:2.3.0
    entrypoint: /usr/src/whally/development-entrypoint.sh
    command: bash
    volumes:
      - .:/usr/src/whally
      - gems:/usr/local/bundle
      - ../datoz-master:/usr/src/whally/datoz
    working_dir: /usr/src/whally
    tty: true
    stdin_open: true
    environment:
      CODECLIMATE_REPO_TOKEN: 1d8bb56c61c6eb5348dd41a22131125ab6bf1328f62b06d36e88275da9e10b7a
